CFLAGS=-std=c99 -pedantic -Wall
LDFLAGS=-lm
OBJECTS=xwb_split.o util.o
COMMON_HEADERS=error_stuff.h util.h
EXE_NAME=xwb_split$(EXE_EXT)

all: $(EXE_NAME)

$(EXE_NAME): $(OBJECTS)

xwb_split.o: xwb_split.c $(COMMON_HEADERS)

util.o: util.c $(COMMON_HEADERS)

clean:
	rm -f $(EXE_NAME) $(OBJECTS)
